cisco_url_shortener/urls.py
from django.conf.urls import include, url
from django.contrib import admin
 
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)), 
    url(r'', include('url_shortener.urls', namespace='url_shortener')),
]

url_shortener/urls.py
from django.conf.urls import url
from . import views
 
urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^phish-error/?$', views.phish_error, name='phish_error'),
    # Redirects the short URL to the original URL
    url(r'^(?P<short_id>\w{6})$', views.redirect_original, name='redirect_original'),
    # Creates a URL's short id and return the short URL
    url(r'^shorten/?$', views.shorten_url, name='shorten_url'),
]

url_shortener/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class URLs(models.Model):
    short_id = models.SlugField(max_length=6, primary_key=True)
    http_url = models.URLField(max_length=1024)
    pub_date = models.DateTimeField(auto_now=True)
    count = models.IntegerField(default=0)
    
    class Meta:
        ordering = ['pub_date']
        verbose_name = 'URL'
        verbose_name_plural = 'URLs'

def __str__(self):
    return self.http_url

url_shortener/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# Create your views here.
import random, string, json
import logging
import urlparse
import requests
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.shortcuts import render, get_object_or_404
from url_shortener.models import URLs
from django.http import HttpResponseRedirect, HttpResponse
from django.conf import settings
from django.views.decorators.csrf import csrf_protect
from ratelimit.decorators import ratelimit

logger = logging.getLogger('django')

@csrf_protect
def index(request):
    """Index page"""
    context = {}
    return render(request, 'url_shortener/index.html', context)

def phish_error(request):
    """Phish error page"""
    context = {}
    return render(request, 'url_shortener/phish-error.html', context)

def redirect_original(request, short_id):
    """Gets object or returns 404 not found error"""
    url = get_object_or_404(URLs, pk=short_id)
    url.count += 1
    url.save()
    # Redirects to phish error page if a Phish URL is detected
    if safeguard_url(url.http_url):
        return HttpResponseRedirect('/phish-error/')
    else:
        return HttpResponseRedirect(url.http_url)

def safeguard_url(url):
    """Safeguards the url using resources from https://www.phishtank.com."""
    data = {'url': url,
            'format': 'json',
            'app_key': settings.APP_KEY}
    try:
        r = requests.post(url=settings.APP_URL, data=data)
        results = json.loads(r.text).get('results')
        if results and results.get('in_database', False) and results.get('phish_id', None) and results.get('valid', False):
            return True
        else:
            return False
    except Exception as e:
        logger.error("Error when making the request to safeguard the url: {}".format(e.message))
        return True

@ratelimit(key='user_or_ip', rate='50/s', block=True, method='POST')
def shorten_url(request):
    """Shortens the provided URL."""
    try:
        url = request.POST.get('url', '')
        short_id = None
        if url:
            response_data = {}
            https = 'http' if 'http:' in url else 'https'
            p = urlparse.urlparse(url, https)
            netloc = p.netloc or p.path
            path = p.path if p.netloc else ''
            p = urlparse.ParseResult(https, netloc, path, *p[3:])
            url = p.geturl()
            try:
                url_obj = URLs.objects.get(http_url=url)
                short_id = url_obj.short_id
            except ObjectDoesNotExist as e:
                logger.error(e.message)
            except MultipleObjectsReturned as e:
                logger.error(e.message)
                URLs.objects.filter(http_url=url).delete()
            if not short_id:
                short_id = get_short_id()
                URLs.objects.create(http_url=url, short_id=short_id)
            if safeguard_url(url):
                response_data['error'] = 'phishing'
            response_data['url'] = settings.SITE_URL + '/' + short_id
            return HttpResponse(json.dumps(response_data),  content_type='application/json')
        else:
            return HttpResponse(json.dumps({'error': 'The given URL is empty.'}), content_type='application/json')
    except Exception as e:
        logger.error(e.message)
        return HttpResponse(json.dumps({'error': e.message}), content_type='application/json')
 
def get_short_id():
    """Creates a new short_id for a URL."""
    length = 6
    char = string.ascii_uppercase + string.digits + string.ascii_lowercase
    # If the randomly generated short_id is used, then returns it
    while True:
        short_id = ''.join(random.choice(char) for x in range(length))
        try:
            temp = URLs.objects.get(pk=short_id)
        except:
            return short_id

url_shortener/templates/url_shortener/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}Welcome to Cisco URL Shortener {% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'url_shortener/css/custom.css' %}" />
    <link rel="icon" href="/favicon.ico?v=2" type="image/x-icon" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <script type="text/javascript">
    $(function() {
      $('#submitButton').click(function() {
        $.ajax({
          type: "POST",
          url: "/shorten/",
          dataType: 'json',
          data: {
            'url' : $('#url').val(),
            'csrfmiddlewaretoken' : $("input[name=csrfmiddlewaretoken]").val()
          }
        })
        .done(returnSuccess)
        .fail(returnFailure)
      });
    });
    
    function returnSuccess(data, textStatus, jqXHR) {
      if (data.url) {
        if (data.error == 'phishing')
            $('#url-result').html('<b style="color:red;">Phishing URL:</b> <a href="' + data.url + '">' + data.url + '</a>');
        else
            $('#url-result').html('<b>Shorten URL:</b> <a href="' + data.url + '">' + data.url + '</a>');
        $('#url').val("");
      } else {
        $('#url-result').text("Do not submit blank."); 
      } 
    }
    
    function returnFailure(jqXHR, textStatus, errorThrown) {
      console.error("Error when fetching the Shorten URL with status: " + jqXHR.status + " " + errorThrown);
    }
  </script>
  <body>
    <div id="wrap">
      <header>
        <h1><a href="{% url 'url_shortener:home' %}">Cisco URL Shortener - </a><small>Shorten your URL</small></h1>
      </header>
      <div id="content">
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </body>
</html>

url_shortener/templates/url_shortener/index.html
{% extends "url_shortener/base.html" %}
{% block title %}Cisco URL Shortner - Shorten your URL!{% endblock %}
{% block content %}
<div class="panel panel-default">
  <div class="panel-body">
    <div class="col-sm-9">
      <input type="text" name="url" id="url" class="form-control input-sm" placeholder="https://www.cisco.com" />
    </div>
    <div class="col-sm-3">
      {% csrf_token %}
      <button id="submitButton" class="btn btn-primary">Submit</button></p> 
    </div>
  </div>
  <div class="panel-footer"><span id="url-result">Enter the URL above and click Submit!</span></div>
</div>
{% endblock %}

url_shortener/templates/url_shortener/phish-error.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
  <link rel="icon" href="/favicon.ico?v=2" type="image/x-icon" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
  <title>Security Threat Detected: Malware Risk</title>

  <style type="text/css">
    body {
    font-family: Arial, Helvetica, sans-serif;
    font-size: 70.5%;
    color:#666666;
    text-align: left;
    }
    .maindoc {
    margin: auto;
    min-width: 750px;
    text-align: left;
    width: 57.69em;
    }
    .answerClass {
    margin-top: 4px;
    margin-bottom: 10px;
    }
    .logo {
    border: 0;
    margin: 0px 0px;
    }
    .not-scary-text {
    font-size: 2;
    }
    .big-scary-text {
    font-size: 4;
    color: red;
    }
  </style>

  <script type="text/javascript">
    function toggleVisibility(objectID) {
    var object = document.getElementById(objectID);
    state = object.style.visibility;
    if (state == 'visible')
    object.style.visibility = 'hidden';
    else
    object.style.visibility = 'visible';
    }

    function toggleDisplay(objectID) {
    var object = document.getElementById(objectID);
    if (object.style.display != 'none') {
    object.style.display = 'none';
    }
    else {
    object.style.display = 'block';
    }
    }
    function toggleInline(objectID) {
    var object = document.getElementById(objectID);
    if (object.style.display != 'none') {
    object.style.display = 'none';
    }
    else {
    object.style.display = 'inline';
    }
    }
  </script>
</head>
<body>
  <div class="maindoc">
    <a href="http://www.cisco.com/en/US/hmpgs/index.html">
      <img src="http://www.cisco.com/web/fw/i/logo.gif" alt="Cisco Systems, Inc. Logo" width="110" height="73" class="logo" >
    </a>
    <h2 class="big-scary-text">
      <b>SECURITY THREAT DETECTED AND BLOCKED</b>
    </h2>
    <p class="not-scary-text">Based on Cisco security threat information, access to the web site supportcloud01.ddns.net has been blocked by Cisco's CSIRT using DNS Response Policy Zone. A hostname, network address, or nameserver associated with supportcloud01.ddns.net has been manually identified by CSIRT as malicious or a security risk which has resulted in this block.
    </p>
    <p class="not-scary-text">In order to support a growing number and variety of devices on the Cisco network, malware protection has shifted from the endpoint, deeper into the network. To enable the most effective protection for computing assets on the Cisco network, CSIRT and Cisco IT jointly rolled out DNS Response Policy Zone on all Cisco DNS servers. These DNS servers are configured to block access to hostnames that are known bad, resolve to known bad IP addresses or are served by known bad nameservers. This DNS firewall technology has been deployed to prevent malicious actors from serving malware or content otherwise harmful to users of the Cisco corporate network.
    </p>
    <p class="not-scary-text">If you believe this page should not be blocked, <a href="https://cisco.service-now.com/sp?id=sc_cat_item&sys_id=a9860b89dbd9a640cb5772fc0f96191d&u_business_service=0fa0f2a5db95c34063339c26db9619ec">open a case </a>providing the following information:
      <ul>
        <li type=disc>Text or screenshot of the corresponding debug information below</li>
        <li type=disc>Business justification for use of the website</li>
      </ul>
    </p>

  <blockquote>
    <table style="border: 1px solid grey">
      <tr>
        <th colspan="2"><h3 class="big-scary-text"><b>Block Reason: Detected a Phish URL!</b></h3></th>
      </tr>
    </table>
  </blockquote>
  <p></p>
  <p></p>
  <hr>
  <div id="faqblock">
  <h2>FAQ</h2>

  <div id="question1" onclick="toggleDisplay('answer1');toggleInline('question1plus');toggleInline('question1minus');">
    <span>
      <img id="question1plus" style="display:inline" src="http://wwwin.cisco.com/dir/resources/120/images/expanded.gif" alt="Plus" >
      <img id="question1minus" style="display:none" src="http://wwwin.cisco.com/dir/resources/120/images/collapse.gif" alt="Minus" >
    </span>
    <b>Question: How do I access the page I'm trying to reach?</b>
  </div>

  <div id="answer1" class="answerClass" style="display:none">Answer: This hostname, the IP address that it resolves to or the DNS server that services its domain name has been intentionally blocked by CSIRT.  The page has been blocked only because it represents a significant security threat to your computer system and information. You will not be able to access this page from the Cisco network until the site's reputation improves and the threat is reduced.
  </div>

  <div id="question2" onclick="toggleDisplay('answer2');toggleInline('question2plus');toggleInline('question2minus');">
    <span>
      <img id="question2plus" style="display:inline" src="http://wwwin.cisco.com/dir/resources/120/images/expanded.gif" alt="Plus" >
      <img id="question2minus" style="display:none" src="http://wwwin.cisco.com/dir/resources/120/images/collapse.gif" alt="Minus" >
    </span>
    <b>Question: Why am I seeing this page?  Why didn't my page load?</b>
  </div>

  <div id="answer2" class="answerClass" style="display:none">Answer: As determined by CSIRT staff the webserver or webpage you are trying to reach has previously been detected as spreading malicious software such as viruses and worms. The risk of allowing this page to load in your browser is HIGH and could result in an attack against your system or personal/Cisco information.
  </div>

  <div id="question3" onclick="toggleDisplay('answer3');toggleInline('question3plus');toggleInline('question3minus');">
    <span>
      <img id="question3plus" style="display:inline" src="http://wwwin.cisco.com/dir/resources/120/images/expanded.gif" alt="Plus" >
      <img id="question3minus" style="display:none" src="http://wwwin.cisco.com/dir/resources/120/images/collapse.gif" alt="Minus" >
    </span>
    <b>Question: How do I learn more about DNS firewalls?</b>
  </div>

  <div id="answer3" class="answerClass" style="display:none">Answer: Please visit the <a href="https://deepthought.isc.org/article/AA-00525/0/Building-DNS-Firewalls-with-Response-Policy-Zones-RPZ.html">Internet Systems Consortium Knowledge Base</a> for more information on using DNS Response Policy Zones to implement a DNS Firewall or visit the internal <a href="https://cspo-wiki.cisco.com/display/csirtpublic/Response+Policy+Zone+-+End+User+Support">RPZ User Page.</a>
  </div>

  <div id="question4" onclick="toggleDisplay('answer4');toggleInline('question4plus');toggleInline('question4minus');">
    <span>
      <img id="question4plus" style="display:inline" src="http://wwwin.cisco.com/dir/resources/120/images/expanded.gif" alt="Plus" >
      <img id="question4minus" style="display:none" src="http://wwwin.cisco.com/dir/resources/120/images/collapse.gif" alt="Minus" >
    </span>
    <b>Question: None of these questions address my issue, where can I get more help?</b>
  </div>

  <div id="answer4" class="answerClass" style="display:none">Answer:  Please contact the GTRC:
    <ul>
      <li>Dial <b>*88*</b> from any Cisco IP phone on the Cisco network</li>
      <li><a href="https://isupportit.cloudapps.cisco.com/">iSupportIT Contact Number list</a></li>
      <li><a href="https://cisco.service-now.com/sp?id=sc_cat_item&sys_id=a9860b89dbd9a640cb5772fc0f96191d&u_business_service=0fa0f2a5db95c34063339c26db9619ec">Open a case via the web (ServiceNow)</a></li>
    </ul>
  </div>

  <hr>
  <p>1992-2017 Cisco Systems Inc. All rights reserved.</p>
  </div>
  </div>
</body>
</html>